/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainLayoutRouteImport } from './routes/_main-layout'
import { Route as AccountResetPasswordRouteImport } from './routes/account/reset-password'
import { Route as MainLayoutSearchRouteImport } from './routes/_main-layout/search'
import { Route as MainLayoutProfileLayoutRouteImport } from './routes/_main-layout/_profile-layout'

const SignUpLazyRouteImport = createFileRoute('/sign-up')()
const LoginLazyRouteImport = createFileRoute('/login')()
const ForgottenPasswordLazyRouteImport = createFileRoute(
  '/forgotten-password',
)()
const MainLayoutIndexLazyRouteImport = createFileRoute('/_main-layout/')()
const AccountVerificationLazyRouteImport = createFileRoute(
  '/account/verification',
)()
const AccountCompleteProfileLazyRouteImport = createFileRoute(
  '/account/complete-profile',
)()
const MainLayoutSavedLazyRouteImport = createFileRoute('/_main-layout/saved')()
const MainLayoutLikedLazyRouteImport = createFileRoute('/_main-layout/liked')()
const MainLayoutActivityLazyRouteImport = createFileRoute(
  '/_main-layout/activity',
)()
const MainLayoutProfileLayoutUsernameIndexLazyRouteImport = createFileRoute(
  '/_main-layout/_profile-layout/$username/',
)()
const MainLayoutUsernameEditIndexLazyRouteImport = createFileRoute(
  '/_main-layout/$username/edit/',
)()
const MainLayoutProfileLayoutUsernameRepliesLazyRouteImport = createFileRoute(
  '/_main-layout/_profile-layout/$username/replies',
)()
const MainLayoutUsernamePostPostIdLazyRouteImport = createFileRoute(
  '/_main-layout/$username/post/$postId',
)()
const MainLayoutUsernameEditUpdateProfileLazyRouteImport = createFileRoute(
  '/_main-layout/$username/edit/update-profile',
)()
const MainLayoutUsernameEditChangeUsernameLazyRouteImport = createFileRoute(
  '/_main-layout/$username/edit/change-username',
)()
const MainLayoutUsernameEditChangePasswordLazyRouteImport = createFileRoute(
  '/_main-layout/$username/edit/change-password',
)()
const MainLayoutUsernameEditChangeEmailIndexLazyRouteImport = createFileRoute(
  '/_main-layout/$username/edit/change-email/',
)()
const MainLayoutUsernameEditChangeEmailConfirmLazyRouteImport = createFileRoute(
  '/_main-layout/$username/edit/change-email/confirm',
)()

const SignUpLazyRoute = SignUpLazyRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/sign-up.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const ForgottenPasswordLazyRoute = ForgottenPasswordLazyRouteImport.update({
  id: '/forgotten-password',
  path: '/forgotten-password',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/forgotten-password.lazy').then((d) => d.Route),
)
const MainLayoutRoute = MainLayoutRouteImport.update({
  id: '/_main-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutIndexLazyRoute = MainLayoutIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any).lazy(() =>
  import('./routes/_main-layout/index.lazy').then((d) => d.Route),
)
const AccountVerificationLazyRoute = AccountVerificationLazyRouteImport.update({
  id: '/account/verification',
  path: '/account/verification',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/account/verification.lazy').then((d) => d.Route),
)
const AccountCompleteProfileLazyRoute =
  AccountCompleteProfileLazyRouteImport.update({
    id: '/account/complete-profile',
    path: '/account/complete-profile',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/account/complete-profile.lazy').then((d) => d.Route),
  )
const MainLayoutSavedLazyRoute = MainLayoutSavedLazyRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => MainLayoutRoute,
} as any).lazy(() =>
  import('./routes/_main-layout/saved.lazy').then((d) => d.Route),
)
const MainLayoutLikedLazyRoute = MainLayoutLikedLazyRouteImport.update({
  id: '/liked',
  path: '/liked',
  getParentRoute: () => MainLayoutRoute,
} as any).lazy(() =>
  import('./routes/_main-layout/liked.lazy').then((d) => d.Route),
)
const MainLayoutActivityLazyRoute = MainLayoutActivityLazyRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => MainLayoutRoute,
} as any).lazy(() =>
  import('./routes/_main-layout/activity.lazy').then((d) => d.Route),
)
const AccountResetPasswordRoute = AccountResetPasswordRouteImport.update({
  id: '/account/reset-password',
  path: '/account/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutSearchRoute = MainLayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => MainLayoutRoute,
} as any).lazy(() =>
  import('./routes/_main-layout/search.lazy').then((d) => d.Route),
)
const MainLayoutProfileLayoutRoute = MainLayoutProfileLayoutRouteImport.update({
  id: '/_profile-layout',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutProfileLayoutUsernameIndexLazyRoute =
  MainLayoutProfileLayoutUsernameIndexLazyRouteImport.update({
    id: '/$username/',
    path: '/$username/',
    getParentRoute: () => MainLayoutProfileLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_main-layout/_profile-layout/$username/index.lazy').then(
      (d) => d.Route,
    ),
  )
const MainLayoutUsernameEditIndexLazyRoute =
  MainLayoutUsernameEditIndexLazyRouteImport.update({
    id: '/$username/edit/',
    path: '/$username/edit/',
    getParentRoute: () => MainLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_main-layout/$username/edit/index.lazy').then(
      (d) => d.Route,
    ),
  )
const MainLayoutProfileLayoutUsernameRepliesLazyRoute =
  MainLayoutProfileLayoutUsernameRepliesLazyRouteImport.update({
    id: '/$username/replies',
    path: '/$username/replies',
    getParentRoute: () => MainLayoutProfileLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_main-layout/_profile-layout/$username/replies.lazy').then(
      (d) => d.Route,
    ),
  )
const MainLayoutUsernamePostPostIdLazyRoute =
  MainLayoutUsernamePostPostIdLazyRouteImport.update({
    id: '/$username/post/$postId',
    path: '/$username/post/$postId',
    getParentRoute: () => MainLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_main-layout/$username/post/$postId.lazy').then(
      (d) => d.Route,
    ),
  )
const MainLayoutUsernameEditUpdateProfileLazyRoute =
  MainLayoutUsernameEditUpdateProfileLazyRouteImport.update({
    id: '/$username/edit/update-profile',
    path: '/$username/edit/update-profile',
    getParentRoute: () => MainLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_main-layout/$username/edit/update-profile.lazy').then(
      (d) => d.Route,
    ),
  )
const MainLayoutUsernameEditChangeUsernameLazyRoute =
  MainLayoutUsernameEditChangeUsernameLazyRouteImport.update({
    id: '/$username/edit/change-username',
    path: '/$username/edit/change-username',
    getParentRoute: () => MainLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_main-layout/$username/edit/change-username.lazy').then(
      (d) => d.Route,
    ),
  )
const MainLayoutUsernameEditChangePasswordLazyRoute =
  MainLayoutUsernameEditChangePasswordLazyRouteImport.update({
    id: '/$username/edit/change-password',
    path: '/$username/edit/change-password',
    getParentRoute: () => MainLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_main-layout/$username/edit/change-password.lazy').then(
      (d) => d.Route,
    ),
  )
const MainLayoutUsernameEditChangeEmailIndexLazyRoute =
  MainLayoutUsernameEditChangeEmailIndexLazyRouteImport.update({
    id: '/$username/edit/change-email/',
    path: '/$username/edit/change-email/',
    getParentRoute: () => MainLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_main-layout/$username/edit/change-email/index.lazy').then(
      (d) => d.Route,
    ),
  )
const MainLayoutUsernameEditChangeEmailConfirmLazyRoute =
  MainLayoutUsernameEditChangeEmailConfirmLazyRouteImport.update({
    id: '/$username/edit/change-email/confirm',
    path: '/$username/edit/change-email/confirm',
    getParentRoute: () => MainLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_main-layout/$username/edit/change-email/confirm.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof MainLayoutIndexLazyRoute
  '/forgotten-password': typeof ForgottenPasswordLazyRoute
  '/login': typeof LoginLazyRoute
  '/sign-up': typeof SignUpLazyRoute
  '/search': typeof MainLayoutSearchRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/activity': typeof MainLayoutActivityLazyRoute
  '/liked': typeof MainLayoutLikedLazyRoute
  '/saved': typeof MainLayoutSavedLazyRoute
  '/account/complete-profile': typeof AccountCompleteProfileLazyRoute
  '/account/verification': typeof AccountVerificationLazyRoute
  '/$username/edit/change-password': typeof MainLayoutUsernameEditChangePasswordLazyRoute
  '/$username/edit/change-username': typeof MainLayoutUsernameEditChangeUsernameLazyRoute
  '/$username/edit/update-profile': typeof MainLayoutUsernameEditUpdateProfileLazyRoute
  '/$username/post/$postId': typeof MainLayoutUsernamePostPostIdLazyRoute
  '/$username/replies': typeof MainLayoutProfileLayoutUsernameRepliesLazyRoute
  '/$username/edit/': typeof MainLayoutUsernameEditIndexLazyRoute
  '/$username/': typeof MainLayoutProfileLayoutUsernameIndexLazyRoute
  '/$username/edit/change-email/confirm': typeof MainLayoutUsernameEditChangeEmailConfirmLazyRoute
  '/$username/edit/change-email/': typeof MainLayoutUsernameEditChangeEmailIndexLazyRoute
}
export interface FileRoutesByTo {
  '/forgotten-password': typeof ForgottenPasswordLazyRoute
  '/login': typeof LoginLazyRoute
  '/sign-up': typeof SignUpLazyRoute
  '/': typeof MainLayoutIndexLazyRoute
  '/search': typeof MainLayoutSearchRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/activity': typeof MainLayoutActivityLazyRoute
  '/liked': typeof MainLayoutLikedLazyRoute
  '/saved': typeof MainLayoutSavedLazyRoute
  '/account/complete-profile': typeof AccountCompleteProfileLazyRoute
  '/account/verification': typeof AccountVerificationLazyRoute
  '/$username/edit/change-password': typeof MainLayoutUsernameEditChangePasswordLazyRoute
  '/$username/edit/change-username': typeof MainLayoutUsernameEditChangeUsernameLazyRoute
  '/$username/edit/update-profile': typeof MainLayoutUsernameEditUpdateProfileLazyRoute
  '/$username/post/$postId': typeof MainLayoutUsernamePostPostIdLazyRoute
  '/$username/replies': typeof MainLayoutProfileLayoutUsernameRepliesLazyRoute
  '/$username/edit': typeof MainLayoutUsernameEditIndexLazyRoute
  '/$username': typeof MainLayoutProfileLayoutUsernameIndexLazyRoute
  '/$username/edit/change-email/confirm': typeof MainLayoutUsernameEditChangeEmailConfirmLazyRoute
  '/$username/edit/change-email': typeof MainLayoutUsernameEditChangeEmailIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main-layout': typeof MainLayoutRouteWithChildren
  '/forgotten-password': typeof ForgottenPasswordLazyRoute
  '/login': typeof LoginLazyRoute
  '/sign-up': typeof SignUpLazyRoute
  '/_main-layout/_profile-layout': typeof MainLayoutProfileLayoutRouteWithChildren
  '/_main-layout/search': typeof MainLayoutSearchRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/_main-layout/activity': typeof MainLayoutActivityLazyRoute
  '/_main-layout/liked': typeof MainLayoutLikedLazyRoute
  '/_main-layout/saved': typeof MainLayoutSavedLazyRoute
  '/account/complete-profile': typeof AccountCompleteProfileLazyRoute
  '/account/verification': typeof AccountVerificationLazyRoute
  '/_main-layout/': typeof MainLayoutIndexLazyRoute
  '/_main-layout/$username/edit/change-password': typeof MainLayoutUsernameEditChangePasswordLazyRoute
  '/_main-layout/$username/edit/change-username': typeof MainLayoutUsernameEditChangeUsernameLazyRoute
  '/_main-layout/$username/edit/update-profile': typeof MainLayoutUsernameEditUpdateProfileLazyRoute
  '/_main-layout/$username/post/$postId': typeof MainLayoutUsernamePostPostIdLazyRoute
  '/_main-layout/_profile-layout/$username/replies': typeof MainLayoutProfileLayoutUsernameRepliesLazyRoute
  '/_main-layout/$username/edit/': typeof MainLayoutUsernameEditIndexLazyRoute
  '/_main-layout/_profile-layout/$username/': typeof MainLayoutProfileLayoutUsernameIndexLazyRoute
  '/_main-layout/$username/edit/change-email/confirm': typeof MainLayoutUsernameEditChangeEmailConfirmLazyRoute
  '/_main-layout/$username/edit/change-email/': typeof MainLayoutUsernameEditChangeEmailIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgotten-password'
    | '/login'
    | '/sign-up'
    | '/search'
    | '/account/reset-password'
    | '/activity'
    | '/liked'
    | '/saved'
    | '/account/complete-profile'
    | '/account/verification'
    | '/$username/edit/change-password'
    | '/$username/edit/change-username'
    | '/$username/edit/update-profile'
    | '/$username/post/$postId'
    | '/$username/replies'
    | '/$username/edit/'
    | '/$username/'
    | '/$username/edit/change-email/confirm'
    | '/$username/edit/change-email/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgotten-password'
    | '/login'
    | '/sign-up'
    | '/'
    | '/search'
    | '/account/reset-password'
    | '/activity'
    | '/liked'
    | '/saved'
    | '/account/complete-profile'
    | '/account/verification'
    | '/$username/edit/change-password'
    | '/$username/edit/change-username'
    | '/$username/edit/update-profile'
    | '/$username/post/$postId'
    | '/$username/replies'
    | '/$username/edit'
    | '/$username'
    | '/$username/edit/change-email/confirm'
    | '/$username/edit/change-email'
  id:
    | '__root__'
    | '/_main-layout'
    | '/forgotten-password'
    | '/login'
    | '/sign-up'
    | '/_main-layout/_profile-layout'
    | '/_main-layout/search'
    | '/account/reset-password'
    | '/_main-layout/activity'
    | '/_main-layout/liked'
    | '/_main-layout/saved'
    | '/account/complete-profile'
    | '/account/verification'
    | '/_main-layout/'
    | '/_main-layout/$username/edit/change-password'
    | '/_main-layout/$username/edit/change-username'
    | '/_main-layout/$username/edit/update-profile'
    | '/_main-layout/$username/post/$postId'
    | '/_main-layout/_profile-layout/$username/replies'
    | '/_main-layout/$username/edit/'
    | '/_main-layout/_profile-layout/$username/'
    | '/_main-layout/$username/edit/change-email/confirm'
    | '/_main-layout/$username/edit/change-email/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
  ForgottenPasswordLazyRoute: typeof ForgottenPasswordLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  SignUpLazyRoute: typeof SignUpLazyRoute
  AccountResetPasswordRoute: typeof AccountResetPasswordRoute
  AccountCompleteProfileLazyRoute: typeof AccountCompleteProfileLazyRoute
  AccountVerificationLazyRoute: typeof AccountVerificationLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgotten-password': {
      id: '/forgotten-password'
      path: '/forgotten-password'
      fullPath: '/forgotten-password'
      preLoaderRoute: typeof ForgottenPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main-layout': {
      id: '/_main-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main-layout/': {
      id: '/_main-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutIndexLazyRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/account/verification': {
      id: '/account/verification'
      path: '/account/verification'
      fullPath: '/account/verification'
      preLoaderRoute: typeof AccountVerificationLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/complete-profile': {
      id: '/account/complete-profile'
      path: '/account/complete-profile'
      fullPath: '/account/complete-profile'
      preLoaderRoute: typeof AccountCompleteProfileLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main-layout/saved': {
      id: '/_main-layout/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof MainLayoutSavedLazyRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/liked': {
      id: '/_main-layout/liked'
      path: '/liked'
      fullPath: '/liked'
      preLoaderRoute: typeof MainLayoutLikedLazyRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/activity': {
      id: '/_main-layout/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof MainLayoutActivityLazyRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/account/reset-password': {
      id: '/account/reset-password'
      path: '/account/reset-password'
      fullPath: '/account/reset-password'
      preLoaderRoute: typeof AccountResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main-layout/search': {
      id: '/_main-layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof MainLayoutSearchRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/_profile-layout': {
      id: '/_main-layout/_profile-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutProfileLayoutRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/_profile-layout/$username/': {
      id: '/_main-layout/_profile-layout/$username/'
      path: '/$username'
      fullPath: '/$username/'
      preLoaderRoute: typeof MainLayoutProfileLayoutUsernameIndexLazyRouteImport
      parentRoute: typeof MainLayoutProfileLayoutRoute
    }
    '/_main-layout/$username/edit/': {
      id: '/_main-layout/$username/edit/'
      path: '/$username/edit'
      fullPath: '/$username/edit/'
      preLoaderRoute: typeof MainLayoutUsernameEditIndexLazyRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/_profile-layout/$username/replies': {
      id: '/_main-layout/_profile-layout/$username/replies'
      path: '/$username/replies'
      fullPath: '/$username/replies'
      preLoaderRoute: typeof MainLayoutProfileLayoutUsernameRepliesLazyRouteImport
      parentRoute: typeof MainLayoutProfileLayoutRoute
    }
    '/_main-layout/$username/post/$postId': {
      id: '/_main-layout/$username/post/$postId'
      path: '/$username/post/$postId'
      fullPath: '/$username/post/$postId'
      preLoaderRoute: typeof MainLayoutUsernamePostPostIdLazyRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/$username/edit/update-profile': {
      id: '/_main-layout/$username/edit/update-profile'
      path: '/$username/edit/update-profile'
      fullPath: '/$username/edit/update-profile'
      preLoaderRoute: typeof MainLayoutUsernameEditUpdateProfileLazyRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/$username/edit/change-username': {
      id: '/_main-layout/$username/edit/change-username'
      path: '/$username/edit/change-username'
      fullPath: '/$username/edit/change-username'
      preLoaderRoute: typeof MainLayoutUsernameEditChangeUsernameLazyRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/$username/edit/change-password': {
      id: '/_main-layout/$username/edit/change-password'
      path: '/$username/edit/change-password'
      fullPath: '/$username/edit/change-password'
      preLoaderRoute: typeof MainLayoutUsernameEditChangePasswordLazyRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/$username/edit/change-email/': {
      id: '/_main-layout/$username/edit/change-email/'
      path: '/$username/edit/change-email'
      fullPath: '/$username/edit/change-email/'
      preLoaderRoute: typeof MainLayoutUsernameEditChangeEmailIndexLazyRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/$username/edit/change-email/confirm': {
      id: '/_main-layout/$username/edit/change-email/confirm'
      path: '/$username/edit/change-email/confirm'
      fullPath: '/$username/edit/change-email/confirm'
      preLoaderRoute: typeof MainLayoutUsernameEditChangeEmailConfirmLazyRouteImport
      parentRoute: typeof MainLayoutRoute
    }
  }
}

interface MainLayoutProfileLayoutRouteChildren {
  MainLayoutProfileLayoutUsernameRepliesLazyRoute: typeof MainLayoutProfileLayoutUsernameRepliesLazyRoute
  MainLayoutProfileLayoutUsernameIndexLazyRoute: typeof MainLayoutProfileLayoutUsernameIndexLazyRoute
}

const MainLayoutProfileLayoutRouteChildren: MainLayoutProfileLayoutRouteChildren =
  {
    MainLayoutProfileLayoutUsernameRepliesLazyRoute:
      MainLayoutProfileLayoutUsernameRepliesLazyRoute,
    MainLayoutProfileLayoutUsernameIndexLazyRoute:
      MainLayoutProfileLayoutUsernameIndexLazyRoute,
  }

const MainLayoutProfileLayoutRouteWithChildren =
  MainLayoutProfileLayoutRoute._addFileChildren(
    MainLayoutProfileLayoutRouteChildren,
  )

interface MainLayoutRouteChildren {
  MainLayoutProfileLayoutRoute: typeof MainLayoutProfileLayoutRouteWithChildren
  MainLayoutSearchRoute: typeof MainLayoutSearchRoute
  MainLayoutActivityLazyRoute: typeof MainLayoutActivityLazyRoute
  MainLayoutLikedLazyRoute: typeof MainLayoutLikedLazyRoute
  MainLayoutSavedLazyRoute: typeof MainLayoutSavedLazyRoute
  MainLayoutIndexLazyRoute: typeof MainLayoutIndexLazyRoute
  MainLayoutUsernameEditChangePasswordLazyRoute: typeof MainLayoutUsernameEditChangePasswordLazyRoute
  MainLayoutUsernameEditChangeUsernameLazyRoute: typeof MainLayoutUsernameEditChangeUsernameLazyRoute
  MainLayoutUsernameEditUpdateProfileLazyRoute: typeof MainLayoutUsernameEditUpdateProfileLazyRoute
  MainLayoutUsernamePostPostIdLazyRoute: typeof MainLayoutUsernamePostPostIdLazyRoute
  MainLayoutUsernameEditIndexLazyRoute: typeof MainLayoutUsernameEditIndexLazyRoute
  MainLayoutUsernameEditChangeEmailConfirmLazyRoute: typeof MainLayoutUsernameEditChangeEmailConfirmLazyRoute
  MainLayoutUsernameEditChangeEmailIndexLazyRoute: typeof MainLayoutUsernameEditChangeEmailIndexLazyRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainLayoutProfileLayoutRoute: MainLayoutProfileLayoutRouteWithChildren,
  MainLayoutSearchRoute: MainLayoutSearchRoute,
  MainLayoutActivityLazyRoute: MainLayoutActivityLazyRoute,
  MainLayoutLikedLazyRoute: MainLayoutLikedLazyRoute,
  MainLayoutSavedLazyRoute: MainLayoutSavedLazyRoute,
  MainLayoutIndexLazyRoute: MainLayoutIndexLazyRoute,
  MainLayoutUsernameEditChangePasswordLazyRoute:
    MainLayoutUsernameEditChangePasswordLazyRoute,
  MainLayoutUsernameEditChangeUsernameLazyRoute:
    MainLayoutUsernameEditChangeUsernameLazyRoute,
  MainLayoutUsernameEditUpdateProfileLazyRoute:
    MainLayoutUsernameEditUpdateProfileLazyRoute,
  MainLayoutUsernamePostPostIdLazyRoute: MainLayoutUsernamePostPostIdLazyRoute,
  MainLayoutUsernameEditIndexLazyRoute: MainLayoutUsernameEditIndexLazyRoute,
  MainLayoutUsernameEditChangeEmailConfirmLazyRoute:
    MainLayoutUsernameEditChangeEmailConfirmLazyRoute,
  MainLayoutUsernameEditChangeEmailIndexLazyRoute:
    MainLayoutUsernameEditChangeEmailIndexLazyRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainLayoutRoute: MainLayoutRouteWithChildren,
  ForgottenPasswordLazyRoute: ForgottenPasswordLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  SignUpLazyRoute: SignUpLazyRoute,
  AccountResetPasswordRoute: AccountResetPasswordRoute,
  AccountCompleteProfileLazyRoute: AccountCompleteProfileLazyRoute,
  AccountVerificationLazyRoute: AccountVerificationLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
